"""Generate device-side agent scripts and upload them with mpremote."""

from __future__ import annotations

import re
import shutil
import subprocess
import tempfile
from pathlib import Path

from codetocad.communication import (
    MqttCommunication,
    SerialCommunication,
    WifiCommunication,
)
from codetocad.microcontroller import (
    I2CBus,
    Microcontroller,
    MicrocontrollerRuntime,
    SPIBus,
    UARTBus,
)

_PYTHON_RUNTIME_DRIVERS = (
    "digital_in",
    "encoder",
    "pwm",
    "digital_out",
    "servo",
    "dc_motor",
    "stepper",
    "i2c_register",
    "current_ina219",
    "imu_mpu6050",
    "pwm_pca9685",
    "servo_pca9685",
    "dc_motor_drv8830",
    "vesc_uart",
    "adc_mcp3008",
)

_PCA9685_DRIVERS = ("pwm_pca9685", "servo_pca9685")
_VESC_DRIVERS = ("vesc_uart",)


def _bus_var(bus) -> str:
    return f"_{bus.kind}{bus.id}"


def _identifier(name: str) -> str:
    return re.sub(r"\W", "_", name)


def generate_main_py(mcu: Microcontroller) -> str:
    """The agent script for ``mcu``: MicroPython ``main.py`` for
    MicroPython boards, a gpiozero-based CPython script for Python boards."""
    if mcu.board.runtime is MicrocontrollerRuntime.MICROPYTHON:
        return _generate_micropython(mcu)
    return _generate_python(mcu)


# -- MicroPython --


def _generate_micropython(mcu: Microcontroller) -> str:
    machine_imports = ["Pin", "ADC", "PWM"]
    for bus_class, machine_name in ((I2CBus, "I2C"), (SPIBus, "SPI"), (UARTBus, "UART")):
        if any(isinstance(bus, bus_class) for bus in mcu.buses):
            machine_imports.append(machine_name)
    sections = [
        f'"""CodeToCAD agent for {mcu.name or "microcontroller"} '
        f'({mcu.board.board_name}). Generated by codetocad; do not edit."""',
        "import json",
        "import time",
        f"from machine import {', '.join(machine_imports)}",
        "",
        f"LOGIC_VOLTAGE = {mcu.board.logic_voltage}",
        "",
        "def _adc_volts(adc):",
        "    try:",
        "        return adc.read_u16() / 65535 * LOGIC_VOLTAGE",
        "    except AttributeError:",
        f"        return adc.read() / {mcu.board.adc_max or 4095} * LOGIC_VOLTAGE",
        "",
        "def _set_duty(pwm, fraction):",
        "    fraction = min(1.0, max(0.0, fraction))",
        "    try:",
        "        pwm.duty_u16(int(fraction * 65535))",
        "    except AttributeError:",
        "        pwm.duty(int(fraction * 1023))",
        "",
        _micropython_comm(mcu),
    ]
    sections.extend(_micropython_buses(mcu))
    drivers_used = {binding.driver for binding in mcu.bindings}
    if drivers_used & set(_PCA9685_DRIVERS):
        sections.append(_MICROPYTHON_PCA9685_HELPERS)
    if drivers_used & set(_VESC_DRIVERS):
        sections.append(_VESC_HELPERS)
    for binding in mcu.bindings:
        sections.append(_MICROPYTHON_DRIVERS[binding.driver](binding))
    sections.append(_dispatch_tables(mcu))
    sections.append(_MICROPYTHON_MAIN_LOOP)
    return "\n".join(sections)


def _micropython_buses(mcu: Microcontroller) -> list[str]:
    lines = []
    for bus in mcu.buses:
        var = _bus_var(bus)
        if isinstance(bus, I2CBus):
            lines.append(
                f"{var} = I2C({bus.id}, sda=Pin({bus.sda}), scl=Pin({bus.scl}), "
                f"freq={bus.frequency_hz})"
            )
        elif isinstance(bus, SPIBus):
            lines.append(
                f"{var} = SPI({bus.id}, baudrate={bus.baud_rate}, "
                f"sck=Pin({bus.sck}), mosi=Pin({bus.mosi}), miso=Pin({bus.miso}))"
            )
        elif isinstance(bus, UARTBus):
            tx_rx = ""
            if bus.tx is not None and bus.rx is not None:
                tx_rx = f", tx=Pin({bus.tx}), rx=Pin({bus.rx})"
            lines.append(f"{var} = UART({bus.id}, baudrate={bus.baud_rate}{tx_rx})")
    if lines:
        lines = ["# --- buses ---"] + lines + [""]
    return lines


def _micropython_comm(mcu: Microcontroller) -> str:
    communication = mcu.communication
    if isinstance(communication, WifiCommunication):
        return _MICROPYTHON_WIFI.format(
            ssid=communication.ssid,
            password=communication.password,
            port=communication.port,
        )
    if isinstance(communication, MqttCommunication):
        return _MICROPYTHON_MQTT.format(
            broker=communication.broker,
            port=communication.port,
            command_topic=communication.command_topic,
            telemetry_topic=communication.telemetry_topic,
            username=communication.username,
            password=communication.password,
            client_id=_identifier(mcu.name or "codetocad"),
        )
    # Serial/Bluetooth-SPP (and the default): JSON lines on the USB/UART REPL.
    return _MICROPYTHON_SERIAL


_MICROPYTHON_SERIAL = '''\
# --- communication: serial (JSON lines over the USB/UART REPL) ---
import select
import sys

_stdin_poll = select.poll()
_stdin_poll.register(sys.stdin, select.POLLIN)

def comm_init():
    pass

def comm_read_lines():
    lines = []
    while _stdin_poll.poll(0):
        line = sys.stdin.readline()
        if not line:
            break
        lines.append(line)
    return lines

def comm_send(message):
    print(json.dumps(message))
'''

_MICROPYTHON_WIFI = '''\
# --- communication: wifi (TCP server, JSON lines) ---
import network
import socket

WIFI_SSID = {ssid!r}
WIFI_PASSWORD = {password!r}
TCP_PORT = {port}

_client = None
_rx_buffer = b""

def comm_init():
    global _client
    wlan = network.WLAN(network.STA_IF)
    wlan.active(True)
    if WIFI_SSID and not wlan.isconnected():
        wlan.connect(WIFI_SSID, WIFI_PASSWORD)
        while not wlan.isconnected():
            time.sleep(0.2)
    print("codetocad: wifi connected", wlan.ifconfig()[0])
    server = socket.socket()
    server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    server.bind(("0.0.0.0", TCP_PORT))
    server.listen(1)
    _client, _ = server.accept()
    _client.setblocking(False)

def comm_read_lines():
    global _rx_buffer
    if _client is None:
        return []
    try:
        while True:
            chunk = _client.recv(1024)
            if not chunk:
                break
            _rx_buffer += chunk
    except OSError:
        pass
    lines = _rx_buffer.split(b"\\n")
    _rx_buffer = lines.pop()
    return [line.decode() for line in lines]

def comm_send(message):
    if _client is not None:
        _client.send(json.dumps(message).encode() + b"\\n")
'''

_MICROPYTHON_MQTT = '''\
# --- communication: MQTT (umqtt.simple; install with `mpremote mip install umqtt.simple`) ---
from umqtt.simple import MQTTClient

_incoming = []
_mqtt = None

def _on_mqtt(topic, payload):
    _incoming.append(payload.decode())

def comm_init():
    global _mqtt
    _mqtt = MQTTClient(
        {client_id!r}, {broker!r}, port={port},
        user={username!r}, password={password!r},
    )
    _mqtt.set_callback(_on_mqtt)
    _mqtt.connect()
    _mqtt.subscribe({command_topic!r})

def comm_read_lines():
    _mqtt.check_msg()
    lines = _incoming[:]
    del _incoming[:]
    return lines

def comm_send(message):
    _mqtt.publish({telemetry_topic!r}, json.dumps(message))
'''


def _mp_analog(binding) -> str:
    var = _identifier(binding.name)
    return (
        f"# --- {binding.role} {binding.name!r}: {binding.driver} ---\n"
        f"_{var}_adc = ADC(Pin({binding.pins['pin']}))\n"
        f"try:\n"
        f"    _{var}_adc.atten(ADC.ATTN_11DB)\n"
        f"except AttributeError:\n"
        f"    pass\n"
        f"def read_{var}():\n"
        f"    return _adc_volts(_{var}_adc)\n"
    )


def _mp_digital_in(binding) -> str:
    var = _identifier(binding.name)
    return (
        f"# --- sensor {binding.name!r}: digital_in ---\n"
        f"_{var}_pin = Pin({binding.pins['pin']}, Pin.IN, Pin.PULL_UP)\n"
        f"def read_{var}():\n"
        f"    return _{var}_pin.value()\n"
    )


def _mp_encoder(binding) -> str:
    var = _identifier(binding.name)
    cpr = getattr(binding.device, "counts_per_revolution", 2048)
    cpr = binding.params.get("counts_per_revolution", cpr)
    return (
        f"# --- sensor {binding.name!r}: quadrature encoder ---\n"
        f"_{var}_state = [0, 0, time.ticks_ms()]  # count, last count, last t\n"
        f"_{var}_b = Pin({binding.pins['b']}, Pin.IN)\n"
        f"def _{var}_irq(pin):\n"
        f"    _{var}_state[0] += 1 if _{var}_b.value() else -1\n"
        f"Pin({binding.pins['a']}, Pin.IN).irq(\n"
        f"    trigger=Pin.IRQ_RISING, handler=_{var}_irq)\n"
        f"def read_{var}():\n"
        f"    count = _{var}_state[0]\n"
        f"    now = time.ticks_ms()\n"
        f"    dt = time.ticks_diff(now, _{var}_state[2]) / 1000\n"
        f"    rpm = 0.0\n"
        f"    if dt > 0:\n"
        f"        rpm = (count - _{var}_state[1]) / {cpr} / dt * 60\n"
        f"    _{var}_state[1] = count\n"
        f"    _{var}_state[2] = now\n"
        f"    return {{'count': count, 'rpm': rpm}}\n"
    )


#: MicroPython ``camera`` module framesize constants by (width, height).
_CAMERA_FRAMESIZES = {
    (160, 120): "FRAME_QQVGA",
    (240, 176): "FRAME_HQVGA",
    (320, 240): "FRAME_QVGA",
    (640, 480): "FRAME_VGA",
    (800, 600): "FRAME_SVGA",
    (1024, 768): "FRAME_XGA",
    (1280, 1024): "FRAME_SXGA",
    (1600, 1200): "FRAME_UXGA",
}


def _mp_camera(binding) -> str:
    """An ESP32-CAM (or any board running a camera-enabled MicroPython
    build with the ``camera`` module). Telemetry is
    ``{"frame": <base64 JPEG>}`` — the same shape the simulated camera
    streams (base64 PNG), so the app's ``add_image`` shows either."""
    var = _identifier(binding.name)
    resolution = tuple(getattr(binding.device, "resolution", (320, 240)))
    framesize = binding.params.get(
        "framesize", _CAMERA_FRAMESIZES.get(resolution, "FRAME_QVGA")
    )
    quality = binding.params.get("quality", 12)
    return (
        f"# --- sensor {binding.name!r}: camera (ESP32-CAM) ---\n"
        f"import binascii\n"
        f"import camera\n"
        f"camera.init(0, format=camera.JPEG, framesize=camera.{framesize})\n"
        f"camera.quality({quality})\n"
        f"def read_{var}():\n"
        f"    frame = camera.capture()\n"
        f"    if not frame:\n"
        f"        return None\n"
        f"    return {{'frame': binascii.b2a_base64(frame).decode().strip()}}\n"
    )


def _mp_imu(binding) -> str:
    var = _identifier(binding.name)
    address = binding.address if binding.address is not None else 0x68
    if binding.bus is not None:
        setup = f"_{var}_i2c = {_bus_var(binding.bus)}\n"
    else:  # legacy form: a dedicated bus from sda/scl pins
        setup = (
            f"from machine import I2C\n"
            f"_{var}_i2c = I2C(0, sda=Pin({binding.pins['sda']}), "
            f"scl=Pin({binding.pins['scl']}))\n"
        )
    return (
        f"# --- sensor {binding.name!r}: MPU6050 IMU over I2C ---\n"
        + setup
        + f"_{var}_i2c.writeto_mem({address}, 0x6B, b'\\x00')  # wake\n"
        f"def read_{var}():\n"
        f"    raw = _{var}_i2c.readfrom_mem({address}, 0x3B, 14)\n"
        f"    def s16(i):\n"
        f"        value = (raw[i] << 8) | raw[i + 1]\n"
        f"        return value - 65536 if value > 32767 else value\n"
        f"    return {{\n"
        f"        'accel': [s16(0) / 16384 * 9.80665, s16(2) / 16384 * 9.80665,\n"
        f"                  s16(4) / 16384 * 9.80665],\n"
        f"        'gyro': [s16(8) / 131 * 0.017453, s16(10) / 131 * 0.017453,\n"
        f"                 s16(12) / 131 * 0.017453],\n"
        f"    }}\n"
    )


_VESC_HELPERS = '''\
# --- VESC UART framing (short packets, CRC16-XMODEM) ---
def _vesc_crc16(payload):
    crc = 0
    for byte in payload:
        crc ^= byte << 8
        for _ in range(8):
            if crc & 0x8000:
                crc = ((crc << 1) ^ 0x1021) & 0xFFFF
            else:
                crc = (crc << 1) & 0xFFFF
    return crc

def _vesc_command(command_id, value):
    payload = bytes([command_id]) + (int(value) & 0xFFFFFFFF).to_bytes(4, "big")
    return (bytes([2, len(payload)]) + payload
            + _vesc_crc16(payload).to_bytes(2, "big") + b"\\x03")
'''

_MICROPYTHON_PCA9685_HELPERS = '''\
# --- PCA9685 16-channel PWM driver helpers ---
def _pca9685_init(i2c, address, freq):
    i2c.writeto_mem(address, 0x00, b"\\x10")  # sleep to set prescale
    prescale = int(25000000 / 4096 / freq + 0.5) - 1
    i2c.writeto_mem(address, 0xFE, bytes([prescale]))
    i2c.writeto_mem(address, 0x00, b"\\xa0")  # restart + auto-increment

def _pca9685_set(i2c, address, channel, fraction):
    ticks = int(min(1.0, max(0.0, fraction)) * 4095)
    i2c.writeto_mem(address, 0x06 + 4 * channel,
                    bytes([0, 0, ticks & 0xFF, ticks >> 8]))
'''


def _mp_i2c_register(binding) -> str:
    var = _identifier(binding.name)
    params = binding.params
    if "register" not in params:
        raise ValueError(
            f"i2c_register binding {binding.name!r} needs "
            'params={"register": <reg>, ...} (optional: length, scale, signed)'
        )
    register = params["register"]
    length = params.get("length", 2)
    scale = params.get("scale", 1.0)
    signed = params.get("signed", False)
    lines = [
        f"# --- sensor {binding.name!r}: I2C register read ---",
        f"def read_{var}():",
        f"    raw = int.from_bytes({_bus_var(binding.bus)}.readfrom_mem("
        f"{binding.address}, {register}, {length}), 'big')",
    ]
    if signed:
        lines += [
            f"    if raw >= {1 << (8 * length - 1)}:",
            f"        raw -= {1 << (8 * length)}",
        ]
    lines.append(f"    return raw * {scale}")
    return "\n".join(lines) + "\n"


def _mp_current_ina219(binding) -> str:
    var = _identifier(binding.name)
    shunt_ohms = binding.params.get("shunt_ohms", 0.1)
    return (
        f"# --- sensor {binding.name!r}: INA219 current sensor (shunt "
        f"voltage register, LSB 10uV) ---\n"
        f"def read_{var}():\n"
        f"    raw = int.from_bytes({_bus_var(binding.bus)}.readfrom_mem("
        f"{binding.address}, 0x01, 2), 'big')\n"
        f"    if raw >= 32768:\n"
        f"        raw -= 65536\n"
        f"    return raw * 1e-05 / {shunt_ohms}\n"
    )


def _mp_adc_mcp3008(binding) -> str:
    var = _identifier(binding.name)
    channel = binding.params.get("channel", 0)
    vref = binding.params.get("vref", 3.3)
    return (
        f"# --- sensor {binding.name!r}: MCP3008 ADC channel {channel} over SPI ---\n"
        f"_{var}_cs = Pin({binding.pins['cs']}, Pin.OUT, value=1)\n"
        f"def read_{var}():\n"
        f"    buf = bytearray(3)\n"
        f"    _{var}_cs.value(0)\n"
        f"    {_bus_var(binding.bus)}.write_readinto(bytes([1, {(8 + channel) << 4}, 0]), buf)\n"
        f"    _{var}_cs.value(1)\n"
        f"    return (((buf[1] & 3) << 8) | buf[2]) / 1023 * {vref}\n"
    )


def _mp_pwm_pca9685(binding) -> str:
    var = _identifier(binding.name)
    channel = binding.params.get("channel", 0)
    freq = binding.params.get("frequency_hz", 1000)
    bus = _bus_var(binding.bus)
    return (
        f"# --- actuator {binding.name!r}: PCA9685 PWM channel {channel} ---\n"
        f"_pca9685_init({bus}, {binding.address}, {freq})\n"
        f"def command_{var}(value):\n"
        f"    _pca9685_set({bus}, {binding.address}, {channel}, float(value))\n"
    )


def _mp_servo_pca9685(binding) -> str:
    var = _identifier(binding.name)
    channel = binding.params.get("channel", 0)
    bus = _bus_var(binding.bus)
    return (
        f"# --- actuator {binding.name!r}: servo on PCA9685 channel {channel} "
        f"(500-2500us at 50Hz) ---\n"
        f"_pca9685_init({bus}, {binding.address}, 50)\n"
        f"def command_{var}(degrees):\n"
        f"    pulse_us = 500 + min(180, max(0, float(degrees))) / 180 * 2000\n"
        f"    _pca9685_set({bus}, {binding.address}, {channel}, pulse_us / 20000)\n"
    )


def _dc_motor_dispatch(var: str, max_rpm) -> str:
    return (
        f"def command_{var}(value):\n"
        f"    if not isinstance(value, dict):\n"
        f"        value = {{'duty': float(value)}}\n"
        f"    if value.get('stop'):\n"
        f"        _{var}_duty(0.0)\n"
        f"    elif 'duty' in value:\n"
        f"        _{var}_duty(float(value['duty']))\n"
        f"    elif 'velocity_rpm' in value:\n"
        f"        _{var}_duty(float(value['velocity_rpm']) / {max_rpm})\n"
    )


def _dc_motor_drv8830(binding) -> str:
    """DRV8830 I2C motor driver (works verbatim on both runtimes; the
    Python variant monkey-patches writeto_mem onto smbus2)."""
    var = _identifier(binding.name)
    max_rpm = binding.params.get(
        "max_rpm", getattr(binding.device, "no_load_speed_rpm", None) or 300
    )
    bus = _bus_var(binding.bus)
    return (
        f"# --- actuator {binding.name!r}: DRV8830 I2C motor driver ---\n"
        f"def _{var}_duty(duty):\n"
        f"    duty = min(1.0, max(-1.0, duty))\n"
        f"    if abs(duty) < 0.02:\n"
        f"        {bus}.writeto_mem({binding.address}, 0x00, b'\\x03')  # brake\n"
        f"    else:\n"
        f"        vset = max(0x06, int(abs(duty) * 0x3F))\n"
        f"        bits = 1 if duty >= 0 else 2\n"
        f"        {bus}.writeto_mem({binding.address}, 0x00, bytes([(vset << 2) | bits]))\n"
        + _dc_motor_dispatch(var, max_rpm)
    )


def _vesc_uart(binding) -> str:
    """VESC over the microcontroller's UART. Shared by both runtimes:
    the bus variable exposes ``write()`` (machine.UART and pyserial both
    do)."""
    var = _identifier(binding.name)
    pole_pairs = binding.params.get(
        "pole_pairs", getattr(binding.device, "pole_pairs", None) or 1
    )
    bus = _bus_var(binding.bus)
    return (
        f"# --- actuator {binding.name!r}: VESC over UART "
        f"(COMM_SET_DUTY=5, COMM_SET_CURRENT=6, COMM_SET_RPM=8) ---\n"
        f"def command_{var}(value):\n"
        f"    if not isinstance(value, dict):\n"
        f"        value = {{'duty': float(value)}}\n"
        f"    if value.get('stop'):\n"
        f"        {bus}.write(_vesc_command(6, 0))\n"
        f"    elif 'duty' in value:\n"
        f"        {bus}.write(_vesc_command(5, float(value['duty']) * 100000))\n"
        f"    elif 'velocity_rpm' in value:\n"
        f"        {bus}.write(_vesc_command(8, float(value['velocity_rpm']) * {pole_pairs}))\n"
        f"    elif 'current_amps' in value:\n"
        f"        {bus}.write(_vesc_command(6, float(value['current_amps']) * 1000))\n"
    )


def _mp_pwm(binding) -> str:
    var = _identifier(binding.name)
    freq = binding.params.get("frequency_hz", 1000)
    return (
        f"# --- actuator {binding.name!r}: pwm ---\n"
        f"_{var}_pwm = PWM(Pin({binding.pins['pin']}), freq={freq})\n"
        f"def command_{var}(value):\n"
        f"    _set_duty(_{var}_pwm, float(value))\n"
    )


def _mp_digital_out(binding) -> str:
    var = _identifier(binding.name)
    return (
        f"# --- actuator {binding.name!r}: digital_out ---\n"
        f"_{var}_pin = Pin({binding.pins['pin']}, Pin.OUT)\n"
        f"def command_{var}(value):\n"
        f"    _{var}_pin.value(1 if value else 0)\n"
    )


def _mp_servo(binding) -> str:
    var = _identifier(binding.name)
    return (
        f"# --- actuator {binding.name!r}: servo (500-2500us at 50Hz) ---\n"
        f"_{var}_pwm = PWM(Pin({binding.pins['pin']}), freq=50)\n"
        f"def command_{var}(degrees):\n"
        f"    pulse_us = 500 + min(180, max(0, float(degrees))) / 180 * 2000\n"
        f"    _set_duty(_{var}_pwm, pulse_us / 20000)\n"
    )


def _mp_dc_motor(binding) -> str:
    var = _identifier(binding.name)
    max_rpm = binding.params.get(
        "max_rpm", getattr(binding.device, "no_load_speed_rpm", None) or 300
    )
    freq = binding.params.get("frequency_hz", 1000)
    return (
        f"# --- actuator {binding.name!r}: dc_motor (H-bridge PWM+DIR) ---\n"
        f"_{var}_pwm = PWM(Pin({binding.pins['pwm']}), freq={freq})\n"
        f"_{var}_dir = Pin({binding.pins['dir']}, Pin.OUT)\n"
        f"def _{var}_duty(duty):\n"
        f"    _{var}_dir.value(1 if duty >= 0 else 0)\n"
        f"    _set_duty(_{var}_pwm, abs(duty))\n"
        f"def command_{var}(value):\n"
        f"    if not isinstance(value, dict):\n"
        f"        value = {{'duty': float(value)}}\n"
        f"    if value.get('stop'):\n"
        f"        _{var}_duty(0.0)\n"
        f"    elif 'duty' in value:\n"
        f"        _{var}_duty(float(value['duty']))\n"
        f"    elif 'velocity_rpm' in value:\n"
        f"        _{var}_duty(float(value['velocity_rpm']) / {max_rpm})\n"
    )


def _mp_stepper(binding) -> str:
    var = _identifier(binding.name)
    step_delay_us = binding.params.get("step_delay_us", 800)
    return (
        f"# --- actuator {binding.name!r}: stepper (STEP/DIR) ---\n"
        f"_{var}_step = Pin({binding.pins['step']}, Pin.OUT)\n"
        f"_{var}_dir = Pin({binding.pins['dir']}, Pin.OUT)\n"
        f"_{var}_position = [0]\n"
        f"def _{var}_move(steps):\n"
        f"    _{var}_dir.value(1 if steps >= 0 else 0)\n"
        f"    for _ in range(abs(int(steps))):\n"
        f"        _{var}_step.value(1)\n"
        f"        time.sleep_us({step_delay_us})\n"
        f"        _{var}_step.value(0)\n"
        f"        time.sleep_us({step_delay_us})\n"
        f"    _{var}_position[0] += int(steps)\n"
        f"def command_{var}(value):\n"
        f"    if not isinstance(value, dict):\n"
        f"        value = {{'steps': int(value)}}\n"
        f"    if 'steps' in value:\n"
        f"        _{var}_move(value['steps'])\n"
        f"    elif 'position_steps' in value:\n"
        f"        _{var}_move(int(value['position_steps']) - _{var}_position[0])\n"
        f"    elif value.get('stop'):\n"
        f"        pass\n"
    )


_MICROPYTHON_DRIVERS = {
    "analog": _mp_analog,
    "current": _mp_analog,
    "digital_in": _mp_digital_in,
    "encoder": _mp_encoder,
    "imu_mpu6050": _mp_imu,
    "camera": _mp_camera,
    "pwm": _mp_pwm,
    "digital_out": _mp_digital_out,
    "servo": _mp_servo,
    "dc_motor": _mp_dc_motor,
    "stepper": _mp_stepper,
    "i2c_register": _mp_i2c_register,
    "current_ina219": _mp_current_ina219,
    "adc_mcp3008": _mp_adc_mcp3008,
    "pwm_pca9685": _mp_pwm_pca9685,
    "servo_pca9685": _mp_servo_pca9685,
    "dc_motor_drv8830": _dc_motor_drv8830,
    "vesc_uart": _vesc_uart,
}


def _dispatch_tables(mcu: Microcontroller) -> str:
    commands = ", ".join(
        f"{binding.name!r}: command_{_identifier(binding.name)}"
        for binding in mcu.actuators
    )
    sensors = ", ".join(
        f"[{binding.name!r}, read_{_identifier(binding.name)}, "
        f"{int(1000 / (binding.sample_rate_hz or 10))}, 0]"
        for binding in mcu.sensors
    )
    return f"COMMANDS = {{{commands}}}\nSENSORS = [{sensors}]\n"


_MICROPYTHON_MAIN_LOOP = '''\
def main():
    comm_init()
    while True:
        for line in comm_read_lines():
            line = line.strip()
            if not line:
                continue
            try:
                message = json.loads(line)
            except ValueError:
                continue
            if message.get("type") == "command":
                handler = COMMANDS.get(message.get("name"))
                if handler:
                    handler(message.get("value"))
        now = time.ticks_ms()
        for entry in SENSORS:
            if time.ticks_diff(now, entry[3]) >= 0:
                entry[3] = time.ticks_add(now, entry[2])
                try:
                    value = entry[1]()
                except Exception:
                    continue
                comm_send({"type": "telemetry", "name": entry[0],
                           "value": value, "t": time.ticks_ms() / 1000})
        time.sleep_ms(2)

main()
'''


# -- Python (Raspberry Pi, gpiozero) --


_PYTHON_GPIO_DRIVERS = (
    "digital_in",
    "encoder",
    "pwm",
    "digital_out",
    "servo",
    "dc_motor",
    "stepper",
)
_PYTHON_I2C_DRIVERS = (
    "i2c_register",
    "current_ina219",
    "imu_mpu6050",
    "pwm_pca9685",
    "servo_pca9685",
    "dc_motor_drv8830",
)


def _generate_python(mcu: Microcontroller) -> str:
    for binding in mcu.bindings:
        if binding.driver not in _PYTHON_RUNTIME_DRIVERS:
            raise ValueError(
                f"Driver {binding.driver!r} (channel {binding.name!r}) is not "
                "supported on Python boards: the Raspberry Pi has no on-board "
                "ADC; read the sensor through an MCP3008 over SPI "
                "(bind_sensor(..., bus=SPIBus(...), cs=8)) or use a "
                "MicroPython board"
            )
        if binding.driver in _PYTHON_I2C_DRIVERS and binding.bus is None:
            raise ValueError(
                f"Channel {binding.name!r}: on Python boards the "
                f"{binding.driver!r} driver needs bus=I2CBus(...) "
                "(bit-banged sda/scl pins are MicroPython-only)"
            )
    drivers_used = {binding.driver for binding in mcu.bindings}
    imports = []
    if drivers_used & set(_PYTHON_GPIO_DRIVERS):
        imports += [
            "from gpiozero import (",
            "    DigitalInputDevice, DigitalOutputDevice, PWMOutputDevice,",
            "    RotaryEncoder, Servo,",
            ")",
        ]
    if "adc_mcp3008" in drivers_used:
        imports.append("from gpiozero import MCP3008")
    if drivers_used & set(_PYTHON_I2C_DRIVERS):
        imports.append("from smbus2 import SMBus")
    if drivers_used & set(_VESC_DRIVERS):
        imports.append("import serial")
    sections = [
        f'"""CodeToCAD agent for {mcu.name or "microcontroller"} '
        f'({mcu.board.board_name}). Generated by codetocad; do not edit.\n\n'
        f'Run on the device with: python3 <this file>  (requires gpiozero;\n'
        f'smbus2 for I2C devices, pyserial for UART devices)"""',
        "import json",
        "import sys",
        "import time",
        "",
        *imports,
        "",
        _python_comm(mcu),
    ]
    sections.extend(_python_buses(mcu))
    if drivers_used & set(_PCA9685_DRIVERS):
        sections.append(_MICROPYTHON_PCA9685_HELPERS)
    if drivers_used & set(_VESC_DRIVERS):
        sections.append(_VESC_HELPERS)
    for binding in mcu.bindings:
        sections.append(_PYTHON_DRIVERS[binding.driver](binding))
    sections.append(_dispatch_tables(mcu))
    sections.append(_PYTHON_MAIN_LOOP)
    return "\n".join(sections)


def _python_buses(mcu: Microcontroller) -> list[str]:
    lines = []
    if any(isinstance(bus, I2CBus) for bus in mcu.buses):
        # Same readfrom_mem/writeto_mem interface as machine.I2C, so the
        # I2C driver snippets are shared between both runtimes.
        lines += [
            "class _I2CAdapter:",
            "    def __init__(self, bus_id):",
            "        self._bus = SMBus(bus_id)",
            "    def readfrom_mem(self, address, register, length):",
            "        return bytes(self._bus.read_i2c_block_data(address, register, length))",
            "    def writeto_mem(self, address, register, data):",
            "        self._bus.write_i2c_block_data(address, register, list(data))",
            "",
        ]
    for bus in mcu.buses:
        var = _bus_var(bus)
        if isinstance(bus, I2CBus):
            lines.append(f"{var} = _I2CAdapter({bus.id})")
        elif isinstance(bus, UARTBus):
            lines.append(f"{var} = serial.Serial({bus.device_path!r}, {bus.baud_rate})")
        # SPI: gpiozero's MCP3008 owns the SPI device itself.
    if lines:
        lines = ["# --- buses ---"] + lines + [""]
    return lines


def _python_comm(mcu: Microcontroller) -> str:
    communication = mcu.communication
    if isinstance(communication, WifiCommunication):
        return _PYTHON_TCP.format(port=communication.port)
    if isinstance(communication, MqttCommunication):
        return _PYTHON_MQTT.format(
            broker=communication.broker,
            port=communication.port,
            command_topic=communication.command_topic,
            telemetry_topic=communication.telemetry_topic,
            username=communication.username,
            password=communication.password,
        )
    return _PYTHON_STDIO


_PYTHON_STDIO = '''\
# --- communication: JSON lines on stdio (works over `ssh pi@host python3 agent.py`) ---
import select

def comm_init():
    pass

def comm_read_lines():
    lines = []
    while select.select([sys.stdin], [], [], 0)[0]:
        line = sys.stdin.readline()
        if not line:
            break
        lines.append(line)
    return lines

def comm_send(message):
    print(json.dumps(message), flush=True)
'''

_PYTHON_TCP = '''\
# --- communication: TCP server (JSON lines) ---
import socket

TCP_PORT = {port}
_client = None
_rx_buffer = b""

def comm_init():
    global _client
    server = socket.socket()
    server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    server.bind(("0.0.0.0", TCP_PORT))
    server.listen(1)
    _client, _ = server.accept()
    _client.setblocking(False)

def comm_read_lines():
    global _rx_buffer
    try:
        while True:
            chunk = _client.recv(4096)
            if not chunk:
                break
            _rx_buffer += chunk
    except BlockingIOError:
        pass
    lines = _rx_buffer.split(b"\\n")
    _rx_buffer = lines.pop()
    return [line.decode() for line in lines]

def comm_send(message):
    if _client is not None:
        _client.sendall(json.dumps(message).encode() + b"\\n")
'''

_PYTHON_MQTT = '''\
# --- communication: MQTT (requires paho-mqtt on the device) ---
import paho.mqtt.client as mqtt

_incoming = []

def _on_message(client, userdata, msg):
    _incoming.append(msg.payload.decode())

def comm_init():
    global _mqtt
    _mqtt = mqtt.Client()
    if {username!r}:
        _mqtt.username_pw_set({username!r}, {password!r})
    _mqtt.on_message = _on_message
    _mqtt.connect({broker!r}, {port})
    _mqtt.subscribe({command_topic!r})
    _mqtt.loop_start()

def comm_read_lines():
    lines = _incoming[:]
    del _incoming[:]
    return lines

def comm_send(message):
    _mqtt.publish({telemetry_topic!r}, json.dumps(message))
'''


def _py_digital_in(binding) -> str:
    var = _identifier(binding.name)
    return (
        f"# --- sensor {binding.name!r}: digital_in ---\n"
        f"_{var}_pin = DigitalInputDevice({binding.pins['pin']}, pull_up=True)\n"
        f"def read_{var}():\n"
        f"    return int(_{var}_pin.value)\n"
    )


def _py_encoder(binding) -> str:
    var = _identifier(binding.name)
    cpr = getattr(binding.device, "counts_per_revolution", 2048)
    cpr = binding.params.get("counts_per_revolution", cpr)
    return (
        f"# --- sensor {binding.name!r}: quadrature encoder ---\n"
        f"_{var}_encoder = RotaryEncoder({binding.pins['a']}, {binding.pins['b']}, max_steps=0)\n"
        f"_{var}_state = [0, time.monotonic()]\n"
        f"def read_{var}():\n"
        f"    count = _{var}_encoder.steps\n"
        f"    now = time.monotonic()\n"
        f"    dt = now - _{var}_state[1]\n"
        f"    rpm = (count - _{var}_state[0]) / {cpr} / dt * 60 if dt > 0 else 0.0\n"
        f"    _{var}_state[0] = count\n"
        f"    _{var}_state[1] = now\n"
        f"    return {{'count': count, 'rpm': rpm}}\n"
    )


def _py_pwm(binding) -> str:
    var = _identifier(binding.name)
    freq = binding.params.get("frequency_hz", 1000)
    return (
        f"# --- actuator {binding.name!r}: pwm ---\n"
        f"_{var}_pwm = PWMOutputDevice({binding.pins['pin']}, frequency={freq})\n"
        f"def command_{var}(value):\n"
        f"    _{var}_pwm.value = min(1.0, max(0.0, float(value)))\n"
    )


def _py_digital_out(binding) -> str:
    var = _identifier(binding.name)
    return (
        f"# --- actuator {binding.name!r}: digital_out ---\n"
        f"_{var}_pin = DigitalOutputDevice({binding.pins['pin']})\n"
        f"def command_{var}(value):\n"
        f"    _{var}_pin.value = 1 if value else 0\n"
    )


def _py_servo(binding) -> str:
    var = _identifier(binding.name)
    return (
        f"# --- actuator {binding.name!r}: servo ---\n"
        f"_{var}_servo = Servo({binding.pins['pin']})\n"
        f"def command_{var}(degrees):\n"
        f"    _{var}_servo.value = min(180, max(0, float(degrees))) / 90 - 1\n"
    )


def _py_dc_motor(binding) -> str:
    var = _identifier(binding.name)
    max_rpm = binding.params.get(
        "max_rpm", getattr(binding.device, "no_load_speed_rpm", None) or 300
    )
    freq = binding.params.get("frequency_hz", 1000)
    return (
        f"# --- actuator {binding.name!r}: dc_motor (H-bridge PWM+DIR) ---\n"
        f"_{var}_pwm = PWMOutputDevice({binding.pins['pwm']}, frequency={freq})\n"
        f"_{var}_dir = DigitalOutputDevice({binding.pins['dir']})\n"
        f"def _{var}_duty(duty):\n"
        f"    _{var}_dir.value = 1 if duty >= 0 else 0\n"
        f"    _{var}_pwm.value = min(1.0, abs(duty))\n"
        f"def command_{var}(value):\n"
        f"    if not isinstance(value, dict):\n"
        f"        value = {{'duty': float(value)}}\n"
        f"    if value.get('stop'):\n"
        f"        _{var}_duty(0.0)\n"
        f"    elif 'duty' in value:\n"
        f"        _{var}_duty(float(value['duty']))\n"
        f"    elif 'velocity_rpm' in value:\n"
        f"        _{var}_duty(float(value['velocity_rpm']) / {max_rpm})\n"
    )


def _py_stepper(binding) -> str:
    var = _identifier(binding.name)
    step_delay = binding.params.get("step_delay_us", 800) / 1e6
    return (
        f"# --- actuator {binding.name!r}: stepper (STEP/DIR) ---\n"
        f"_{var}_step = DigitalOutputDevice({binding.pins['step']})\n"
        f"_{var}_dir = DigitalOutputDevice({binding.pins['dir']})\n"
        f"_{var}_position = [0]\n"
        f"def _{var}_move(steps):\n"
        f"    _{var}_dir.value = 1 if steps >= 0 else 0\n"
        f"    for _ in range(abs(int(steps))):\n"
        f"        _{var}_step.on()\n"
        f"        time.sleep({step_delay})\n"
        f"        _{var}_step.off()\n"
        f"        time.sleep({step_delay})\n"
        f"    _{var}_position[0] += int(steps)\n"
        f"def command_{var}(value):\n"
        f"    if not isinstance(value, dict):\n"
        f"        value = {{'steps': int(value)}}\n"
        f"    if 'steps' in value:\n"
        f"        _{var}_move(value['steps'])\n"
        f"    elif 'position_steps' in value:\n"
        f"        _{var}_move(int(value['position_steps']) - _{var}_position[0])\n"
    )


def _py_adc_mcp3008(binding) -> str:
    var = _identifier(binding.name)
    channel = binding.params.get("channel", 0)
    vref = binding.params.get("vref", 3.3)
    # On the Pi the chip select must be a hardware CE pin: GPIO8 = CE0,
    # GPIO7 = CE1 (gpiozero drives the SPI device, not a soft CS).
    device = 1 if binding.pins.get("cs") == 7 else 0
    return (
        f"# --- sensor {binding.name!r}: MCP3008 ADC channel {channel} "
        f"(hardware SPI CE{device}) ---\n"
        f"_{var}_adc = MCP3008(channel={channel}, device={device})\n"
        f"def read_{var}():\n"
        f"    return _{var}_adc.value * {vref}\n"
    )


_PYTHON_DRIVERS = {
    "digital_in": _py_digital_in,
    "encoder": _py_encoder,
    "pwm": _py_pwm,
    "digital_out": _py_digital_out,
    "servo": _py_servo,
    "dc_motor": _py_dc_motor,
    "stepper": _py_stepper,
    "adc_mcp3008": _py_adc_mcp3008,
    # I2C and UART drivers are shared with the MicroPython generator: the
    # generated _I2CAdapter/serial.Serial expose the same interfaces.
    "i2c_register": _mp_i2c_register,
    "current_ina219": _mp_current_ina219,
    "imu_mpu6050": _mp_imu,
    "pwm_pca9685": _mp_pwm_pca9685,
    "servo_pca9685": _mp_servo_pca9685,
    "dc_motor_drv8830": _dc_motor_drv8830,
    "vesc_uart": _vesc_uart,
}

_PYTHON_MAIN_LOOP = '''\
def main():
    comm_init()
    due = {entry[0]: 0.0 for entry in SENSORS}
    while True:
        for line in comm_read_lines():
            line = line.strip()
            if not line:
                continue
            try:
                message = json.loads(line)
            except ValueError:
                continue
            if message.get("type") == "command":
                handler = COMMANDS.get(message.get("name"))
                if handler:
                    handler(message.get("value"))
        now = time.monotonic()
        for entry in SENSORS:
            if now >= due[entry[0]]:
                due[entry[0]] = now + entry[2] / 1000
                try:
                    value = entry[1]()
                except Exception:
                    continue
                comm_send({"type": "telemetry", "name": entry[0],
                           "value": value, "t": now})
        time.sleep(0.002)

main()
'''


# -- upload --


def upload(mcu: Microcontroller, port: str | None = None) -> str:
    """Generate ``main.py`` for ``mcu`` and copy it onto the board with
    mpremote, then reset so it starts running. Returns the port used."""
    if mcu.board.runtime is not MicrocontrollerRuntime.MICROPYTHON:
        raise ValueError(
            f"{mcu.board.name} is not a MicroPython board; use "
            "mcu.upload(firmware_path=...) and run the script with python3"
        )
    if port is None and isinstance(mcu.communication, SerialCommunication):
        port = mcu.communication.port
    if port is None:
        raise ValueError(
            "No serial port: pass port= or set a SerialCommunication on the "
            "microcontroller"
        )
    mpremote = shutil.which("mpremote")
    if mpremote is None:
        raise RuntimeError(
            "mpremote was not found; install it with: uv sync --extra micropython"
        )
    firmware = generate_main_py(mcu)
    with tempfile.TemporaryDirectory() as tmp_dir:
        main_py = Path(tmp_dir) / "main.py"
        main_py.write_text(firmware)
        subprocess.run(
            [mpremote, "connect", port, "fs", "cp", str(main_py), ":main.py"],
            check=True,
        )
    subprocess.run([mpremote, "connect", port, "reset"], check=True)
    return port
