<!DOCTYPE html>
<html>

<head>
    <title>CodeToCAD Examples</title>
    <style>
        @media print {
            .pagebreak {
                page-break-before: always;
            }
        }

        body {
            -webkit-text-size-adjust: 100%;
            font-family: Lato, proxima-nova, Helvetica Neue, Arial, sans-serif;
            color: #555;
        }

        header {
            margin-top: 20px;
            margin-bottom: 20px;
        }

        img {
            width: 50%;
        }

        .grid-container {
            display: grid;
            gap: 2rem;

                {
                # grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                #
            }
        }

        .grid-container-parameters {
            display: grid;
            gap: 2rem;
            grid-template-columns: 200px auto;
        }

        .grid-item {
            padding: 5px;
        }

        .className {
            list-style: none;
            list-style-image: none;
            font-weight: 700;
            font-size: 110%;
            line-height: normal;
            color: #2980b9;
            box-sizing: border-box;
        }

        .methodName {
            font-family: Lato, proxima-nova, Helvetica Neue, Arial, sans-serif;
            list-style: none;
            list-style-image: none;
            box-sizing: border-box;
            font-weight: 700;
            display: table;
            margin: 6px 0;
            font-size: 90%;
            line-height: normal;
            padding: 6px;
            position: relative;
            margin-top: 0;
            margin-bottom: 6px;
            border: none;
            border-left: 3px solid #ccc;
            background: #f0f0f0;
            color: #555;
        }

        .methods {
            padding: 6px;
            margin: 6px 0;
            font-size: 90%;

        }

        .subHeading {
            -webkit-text-size-adjust: 100%;
            font-size: 16px;
            font-family: Lato, proxima-nova, Helvetica Neue, Arial, sans-serif;
            color: #404040;
            line-height: 24px;
            list-style: none;
            list-style-image: none;
            box-sizing: border-box;
            font-weight: 700;
            margin-bottom: 0;
        }

        .subSubHeading {
            -webkit-text-size-adjust: 100%;
            font-size: 12px;
            font-family: Lato, proxima-nova, Helvetica Neue, Arial, sans-serif;
            color: #404040;
            line-height: 24px;
            list-style: none;
            list-style-image: none;
            box-sizing: border-box;
            font-weight: 700;
            margin-bottom: 0;
        }

        a {
            text-decoration: none;
            color: inherit;
        }

        .chip {
            display: inline-block;
            padding: 0 10px;
            margin-bottom: 2px;
            line-height: 25px;
            border-radius: 25px;
            background-color: #f1f1f1;
            cursor: pointer;
            background: linear-gradient(to bottom, #f1f1f1 50%, #2980b9 50%);
            background-size: 100% 200%;
            background-position: right top;
            transition: all 0.5s ease;
        }

        .chip:hover {
            background-position: right bottom;
            text-decoration: underline;
        }

        pre {
            background: #fff;
            border: 1px solid #ddd;
            border-left: 3px solid #2980b9;
            color: #555;
            page-break-inside: avoid;
            font-family: monospace;
            font-size: 12px;
            margin-bottom: 1.6em;
            max-width: 50%;
            overflow: auto;
            padding: 1em 1.5em;
            display: block;
            word-wrap: break-word;
        }
    </style>
</head>

<body>

    
    <header>
        <h2 style="margin: 0;">CodeToCAD Examples</h2>
        <div>
            Repo: <a href="https://github.com/CodeToCAD/CodeToCAD">https://github.com/CodeToCAD/CodeToCAD</a></div>
        <div>
            Docs: <a
                href="https://codetocad.github.io/CodeToCAD/docs.html">https://codetocad.github.io/CodeToCAD/docs.html</a>
        </div>
    </header>

    

    <div class="" style="width:50%">
        <a href='#Fillets and Chamfers' class="chip">Fillets and Chamfers</a>
        <a href='#Text' class="chip">Text</a>
        <a href='#Calibration Cube' class="chip">Calibration Cube</a>
        <a href='#Patterns' class="chip">Patterns</a>
        <a href='#Sweeping' class="chip">Sweeping</a>
        <a href='#Materials' class="chip">Materials</a>
        <a href='#Stacking Cubes' class="chip">Stacking Cubes</a>
        <a href='#D-Shaft' class="chip">D-Shaft</a>
        <a href='#D-Shaft Knob' class="chip">D-Shaft Knob</a>
        <a href='#Bracelet' class="chip">Bracelet</a>
        <a href='#Ball Joint' class="chip">Ball Joint</a>
        <a href='#Universal Joint' class="chip">Universal Joint</a>
        <a href='#Double Universal Joint' class="chip">Double Universal Joint</a>
        <a href='#Simple Humanoid' class="chip">Simple Humanoid</a>
        <a href='#Import and Export' class="chip">Import and Export</a>
        </div>


    

    <header>
        <h2 style="margin: 0;">Documentation</h2>
    </header>

    <div class="grid-container">
        <div class="grid-item">
            <div class="className" id='Fillets and Chamfers''>Fillets and Chamfers</div>
            
            <div class="methods">
            <div style="
            width: 50%;">You can apply fillets and chamfers to specific edges or faces, or to all the edges or faces. To target a specific edge or face, create a Landmark near the target.</div>
            
            
            <pre>
            
from codetocad import *



blue_material = Material("blue").set_color(0, 0.1, 1.0)

red_material = Material("red").set_color(1.0, 0.1, 0)



Part("fillet_all_edges").create_cube(1, 1, 1).fillet_all_edges(

    "10cm").set_material(blue_material)

Part("chamfer_all_edges").create_cube(1, 1, 1).translate_xyz(

    1.5, 0, 0).set_material(red_material).chamfer_all_edges("10cm")



Part("fillet_all_edgesCylinder").create_cylinder(1/2, 2).translate_xyz(1.5 *

                                                                       2, 0, 0).fillet_all_edges("10cm").set_material(blue_material)

Part("chamfer_all_edgesCylinder").create_cylinder(1/2, 2).translate_xyz(1.5 *

                                                                        3, 0, 0).chamfer_all_edges("10cm").set_material(red_material)



fillet_two_edges = Part("filletTwoEdges").create_cube(1, 1, 1)

fillet_two_edges_edge1 = fillet_two_edges.create_landmark("edge1", max, 0, max)

fillet_two_edges_edge2 = fillet_two_edges.create_landmark("edge2", min, 0, min)

fillet_two_edges.fillet_edges("10cm", [fillet_two_edges_edge1, fillet_two_edges_edge2]).translate_xyz(

    0, 1.5, 0).set_material(blue_material)



chamfer_two_edges = Part("chamferTwoEdges").create_cube(1, 1, 1)

chamfer_two_edges_edge1 = chamfer_two_edges.create_landmark(

    "edge1", max, 0, max)

chamfer_two_edges_edge2 = chamfer_two_edges.create_landmark(

    "edge2", min, 0, min)

chamfer_two_edges.chamfer_edges("10cm", [chamfer_two_edges_edge1, chamfer_two_edges_edge2]).translate_xyz(

    1.5, 1.5, 0).set_material(red_material)



fillet_two_faces = Part("filletTwoFaces").create_cube(1, 1, 1)

fillet_two_faces_face1 = fillet_two_faces.create_landmark("face1", 0, 0, max)

fillet_two_faces_face2 = fillet_two_faces.create_landmark("face2", min, 0, 0)

fillet_two_faces.fillet_faces("10cm", [fillet_two_faces_face1, fillet_two_faces_face2]).translate_xyz(

    1.5*2, 1.5, 0).set_material(blue_material)



chamge_two_faces = Part("chamferTwoFaces").create_cube(1, 1, 1)

chamge_two_faces_face1 = chamge_two_faces.create_landmark("face1", 0, 0, max)

chamge_two_faces_face2 = chamge_two_faces.create_landmark("face2", min, 0, 0)

chamge_two_faces.chamfer_faces("10cm", [chamge_two_faces_face1, chamge_two_faces_face2]).translate_xyz(

    1.5*3, 1.5, 0).set_material(red_material)

            </pre>
        </div>

    </div>

    <div class="grid-item">
            <div class="className" id='Text''>Text</div>
            
            <div class="methods">
            <div style="
            width: 50%;">Use Sketch('sketchName').create_text() to write text. You can apply different text fonts, decorations and sizes. You can also extrude text, or define landmarks relative to the Sketch to mate/joint text to other landmarks.</div>
            
            
            <pre>
            
from pathlib import Path

from codetocad import *



red_material = Material("red").set_color(0.709804, 0.109394, 0.245126, 1.0)

green_material = Material("green").set_color(0.118213, 0.709804, 0.109477, 0.8)

blue_material = Material("blue").set_color(0.0865257, 0.102776, 0.709804, 0.8)



Sketch("CodeToCAD").create_text("Code To CAD",

                                underlined=True).extrude("1cm").set_material(green_material)



Sketch("Small text!").create_text("Small text!",

                                  font_size="15cm", underlined=True).translate_xyz(0, -2, 0)



arial_font_path = str(Path(__file__).parent.absolute()) + "/fonts/arial.ttf"

Sketch("كود تو كاد").create_text("كود تو كاد",

                                 font_file_path=arial_font_path).translate_xyz(-5, 0, 0)





yi_gothic_font_path = str(Path(__file__).parent.absolute()

                          ) + "/fonts/yu_gothic.ttc"

Sketch("curvedTextPath").create_circle(

    "1m").translate_xyz(-5, -5, 0).set_visible(False)

Sketch("コオデツカアド").create_text("コオデツカアド", font_file_path=yi_gothic_font_path).profile(

    "curvedTextPath").translate_xyz(-5, -5, 0).extrude(.1).set_material(red_material)



Sketch("multiline").create_text(

    """Multiline

    Text

        Is

            Awesome!

"""

).translate_xyz(0, -5, 0).extrude(0.1).set_material(blue_material)

            </pre>
        </div>

    </div>

    <div class="grid-item">
            <div class="className" id='Calibration Cube''>Calibration Cube</div>
            
            <div class="methods">
            <div style="
            width: 50%;">Calibration Cubes uses Landmarks on both the Texts' Sketches and the Cube to define where the Text is positioned on the Cube. </div>
            
            
            <pre>
            
from codetocad import *





material = Material("material").set_color(169, 76, 181, 255)





def create_cube(name, size):



    calibartion_cube = Part(name).create_cube(size, size, size)



    calibration_cube_x = calibartion_cube.create_landmark(

        "x", "min+5mm", "max-7mm", max)

    calibration_cube_y = calibartion_cube.create_landmark(

        "y", "max-5mm", "min+5mm", max)

    calibration_cube_z = calibartion_cube.create_landmark(

        "z", center, min, center)

    calibration_cube_size = calibartion_cube.create_landmark(

        "size", "min+1mm", "min+2mm", max)



    z = Sketch("Z").create_text("Z^", "10mm").extrude("1.5mm").rotate_xyz(

        90, 0, 0)

    z_center = z.create_landmark("center", center, center, center)

    Joint(calibration_cube_z, z_center).limit_location_xyz(0, 0, 0)

    calibartion_cube.subtract(z)



    y = Sketch("Y").create_text("Y^", "8mm").extrude("1.5mm")

    y_center = y.create_landmark("center", center, center, center)

    Joint(calibration_cube_y, y_center).limit_location_xyz(0, 0, 0)

    calibartion_cube.subtract(y)



    x = Sketch("X").create_text("X^", "8mm").extrude("1.5mm").rotate_xyz(

        180, 0, 90)

    x_center = x.create_landmark("center", center, center, center)

    Joint(calibration_cube_x, x_center).limit_location_xyz(0, 0, 0)

    calibartion_cube.subtract(x)



    size = Sketch("size").create_text(str(size.value)+"mm",

                                      "4mm").extrude("1.5mm")

    size_center = size.create_landmark("min", min, center, center)

    Joint(calibration_cube_size, size_center).limit_location_xyz(0, 0, 0)

    calibartion_cube.subtract(size)



    calibartion_cube.set_material(material)



    return calibartion_cube





tolerance = "0.2mm"

size = Dimension(20, "mm")



create_cube("calibration_cube19_9", size - tolerance).export(

    "./calibration_cube19_8mm.stl", scale=1000).translate_xyz("-25mm", 0, 0)

create_cube("calibration_cube20mm", size).export(

    "./calibration_cube20mm.stl", scale=1000)

create_cube("calibration_cube20_2", size + tolerance).export(

    "./calibration_cube20_2mm.stl", scale=1000).translate_xyz("25mm", 0, 0)

            </pre>
        </div>

    </div>

    <div class="grid-item">
            <div class="className" id='Patterns''>Patterns</div>
            
            <div class="methods">
            <div style="
            width: 50%;">Use linear and circular patterns to create more of a Part or a Sketch. Note: the Hole method also allows you to pattern holes.</div>
            
            
            <pre>
            
from codetocad import *



linear_cube = Part("Linear Cube").create_cube(

    "5cm", "5cm", "5cm").linear_pattern(10, "7cm", "x")



Part("Circular spheres").create_sphere(1).translate_xyz(0, 5, 0).circular_pattern(

    4, "90d", linear_cube, "z").circular_pattern(6, f"{360/6}d", linear_cube, "x")

            </pre>
        </div>

    </div>

    <div class="grid-item">
            <div class="className" id='Sweeping''>Sweeping</div>
            
            <div class="methods">
            <div style="
            width: 50%;">Apply a sweep modifier to a Sketch to make it follow a profile path, to create a new Part. Note: make sure to sweep the profile, for example `myProfile.sweep('mySketch')`; see `grooveSpiral.sweep(groove)` below.</div>
            
            <img src=' https://raw.githubusercontent.com/CodeToCAD/CodeToCAD/develop/docs/images/coil.png' alt="Image" />
            <pre>
            
from codetocad import *





drum_radius = Dimension.from_string("5mm")

drum_length = Dimension.from_string("15.0 mm")



wire_thickness = Dimension.from_string("1mm")

number_of_windings = 10



groove_spiral = Sketch("grooveSpiral").create_spiral(

    number_of_windings, drum_length, drum_radius)



groove = Sketch("groove").create_circle(wire_thickness/2)



groove_spiral.sweep(groove)

            </pre>
        </div>

    </div>

    <div class="grid-item">
            <div class="className" id='Materials''>Materials</div>
            
            <div class="methods">
            <div style="
            width: 50%;">Apply a material to Parts by creating a Material, and then assigning it to a Part.</div>
            
            <img src=' https://raw.githubusercontent.com/CodeToCAD/CodeToCAD/develop/docs/images/material_cube.png' alt="Image" />
            <pre>
            
from codetocad import *



material = Material("material").set_color(169, 76, 181, 0.8)

Part("Cube").create_cube(1, 1, 1).set_material(material)



material_with_texture = Material(

    "materialWithTexture").add_image_texture("./bark.jpg")

Part("Cylinder").create_cylinder(1, 4).set_material(

    material_with_texture).translate_xyz(5, 0, 0)

            </pre>
        </div>

    </div>

    <div class="grid-item">
            <div class="className" id='Stacking Cubes''>Stacking Cubes</div>
            
            <div class="methods">
            <div style="
            width: 50%;">Cubes and other Entities can be positioned relative to one another using Landmarks.</div>
            
            <img src=' https://raw.githubusercontent.com/CodeToCAD/CodeToCAD/develop/docs/images/stacked_cubes.png' alt="Image" />
            <pre>
            
from codetocad import *



red_material = Material("red").set_color(0.709804, 0.109394, 0.245126, 0.8)

blue_material = Material("blue").set_color(0.0865257, 0.102776, 0.709804, 0.8)

green_material = Material("green").set_color(0.118213, 0.709804, 0.109477, 0.8)





a = Part("a").create_cube(1, 1, 1).set_material(blue_material)

a_top = a.create_landmark("top", center, center, max)

a_bottom = a.create_landmark("bottom", center, center, min)



b = Part("b").create_cube(1, 1, 1).set_material(red_material)

b_bottom = b.create_landmark("bottom", center, center, min)



c = Part("c").create_cube(1, 1, 1).set_material(green_material)

c_top = c.create_landmark("top", center, center, max)



# Joint("a","b","top","bottom").translate_landmark_onto_another()



Joint(a_top, b_bottom)\

    .limit_location_xyz(0, 0, 0)\

    .limit_rotation_xyz(0, 0, 0)



Joint(a_bottom, c_top)\

    .limit_location_xyz(0, 0, 0)\

    .limit_rotation_xyz(0, 0, 0)

            </pre>
        </div>

    </div>

    <div class="grid-item">
            <div class="className" id='D-Shaft''>D-Shaft</div>
            
            <div class="methods">
            <div style="
            width: 50%;">An example that creates a D-keyed shaft using Landmarks and the Subtract modifier.</div>
            
            
            <pre>
            
from dataclasses import dataclass

from codetocad import *





@dataclass

class DShaft:



    shaft_length: Dimension

    radius: Dimension

    d_profile_radius: Dimension

    d_profile_length: Dimension

    tolerance: Dimension = Dimension(0)



    def create(self, name, is_d_shaft_both_sides=False) -> PartInterface:

        shaft_length = self.shaft_length

        radius = self.radius - self.tolerance

        dProfileRadius = self.d_profile_radius - self.tolerance



        d_profile_width = (radius - dProfileRadius) * 2



        shaft = Part(name).create_cylinder(radius, shaft_length)



        d_profile = Part("dProfile").create_cube(

            d_profile_width, radius * 2, self.d_profile_length)



        shaft_left_side = shaft.get_landmark(PresetLandmark.leftTop)

        d_profile_left_side = d_profile.get_landmark(PresetLandmark.leftTop)



        Joint(shaft_left_side, d_profile_left_side).limit_location_xyz(0, 0, 0)



        if is_d_shaft_both_sides:

            d_profile.mirror(shaft, "z", None)



        shaft.subtract(d_profile)



        shaft.get_landmark(PresetLandmark.front).delete()



        return shaft





if __name__ == "__main__":

    shaft_length = Dimension.from_string("13.65mm")

    radius = Dimension.from_string("5.9/2mm")

    d_profile_radius = Dimension.from_string("5.3/2mm")

    d_profile_length = shaft_length/2

    tolerance = Dimension.from_string("0.15mm")



    dShaft = DShaft(shaft_length=shaft_length, radius=radius,

                    d_profile_radius=d_profile_radius, d_profile_length=d_profile_length, tolerance=tolerance).create("shaft")

            </pre>
        </div>

    </div>

    <div class="grid-item">
            <div class="className" id='D-Shaft Knob''>D-Shaft Knob</div>
            
            <div class="methods">
            <div style="
            width: 50%;">An example that imports another CodeToCAD model and uses the Union modifier.</div>
            
            
            <pre>
            
from codetocad import *

from examples.d_shaft import DShaft





def create_d_shaft_sleeve(d_shaft: PartInterface, sleeve_thickness):

    d_shaft_diameter = d_shaft.get_dimensions().y



    sleeve = Part("sleeve").create_cylinder(

        d_shaft_diameter/2 + sleeve_thickness, d_shaft.get_dimensions().z)



    sleeve.subtract(d_shaft, is_transfer_landmarks=True)



    return sleeve





def create_knob(radius):

    knob = Sketch("knob").create_polygon(7, radius, radius).extrude(radius*0.2)



    return knob





if __name__ == "__main__":



    Scene.default().set_default_unit("mm")



    shaft_length = Dimension.from_string("13.65mm")

    radius = Dimension.from_string("5.9/2mm")

    d_profile_radius = Dimension.from_string("5.3/2mm")

    d_profile_length = shaft_length

    tolerance = Dimension.from_string("0.15mm")



    d_shaft = DShaft(shaft_length=shaft_length, radius=radius,

                     d_profile_radius=d_profile_radius, d_profile_length=d_profile_length, tolerance=tolerance).create("shaft")



    sleeve = create_d_shaft_sleeve(d_shaft, "1.5mm")



    knob = create_knob(sleeve.get_dimensions().x)



    Joint(sleeve.create_landmark("top", center, center, max), knob.create_landmark(

        "bottom", center, center, min)).limit_location_xyz(0, 0, 0)



    sleeve.union(knob)

    # sleeve.export("./appliance_knob.stl", scale=1000)

            </pre>
        </div>

    </div>

    <div class="grid-item">
            <div class="className" id='Bracelet''>Bracelet</div>
            
            <div class="methods">
            <div style="
            width: 50%;">You can use the boolean modifiers Subtract, Union and Intersect to manipulate parts.</div>
            
            
            <pre>
            
from codetocad import *



Scene.default().set_default_unit("cm")

Scene.default().create_group("Bracelet")





class Bracelet:

    outer_diameter = "161cm"

    inner_diameter = "81cm"

    thickness = "83cm"



    def create(self):

        bracelet = Part("bracelet") \

            .create_torus(Dimension.from_string(self.inner_diameter)/2, Dimension.from_string(self.outer_diameter)/2)

        bracelet.scale_z(self.thickness)



        return bracelet





class Button:

    radius = "60/2cm"

    depth = "13.6cm"

    inset_radius = "20cm"

    inset_depth = "3cm"



    def create(self):

        button = Part("button") \

            .create_cylinder(self.radius, self.depth)

        button_top = button.get_landmark("top")

        button.fillet_faces("5cm", [button_top])

        button.hole(

            button_top, self.inset_radius, self.inset_depth)

        return button





class Belt:

    outer_radius = "162/2cm"

    inner_radius = "150/2cm"

    thickness = "30cm"



    def create(self):

        belt = Part("belt").create_cylinder(

            self.outer_radius, self.thickness)

        belt.hole(belt.get_landmark("top"),

                  self.inner_radius, self.thickness)

        return belt





# MARK: Create components

bracelet = Bracelet().create()

button = Button().create()

belt = Belt().create()



# Mark: Joint the button to the front of the bracelet

Joint(bracelet.get_landmark("front"), button.get_landmark(

    "top")).limit_location_xyz(0, 0, 0).limit_rotation_xyz(90, 0, 0)

Joint(bracelet.get_landmark("center"), belt.get_landmark(

    "center")).limit_location_xyz(0, 0, 0).limit_rotation_xyz(0, 0, 0)



# Mark: subtract the button and belt from the bracelet:

bracelet.subtract(belt, delete_after_subtract=False)



bracelet.hole(belt.get_landmark("front"),

              button.get_dimensions().x / 2, button.get_dimensions().z, normal_axis="y", flip_axis=True)

belt.hole(belt.get_landmark("front"),

          button.get_dimensions().x / 2, belt.get_dimensions().z, normal_axis="y", flip_axis=True)



# Mark: Assign to a group:



Scene().assign_to_group([bracelet, button, belt], "Bracelet")



# Mark apply materials:

red_material = Material("red").set_color(181, 16, 4)

blue_material = Material("blue").set_color(19, 107, 181)



bracelet.set_material(red_material)

button.set_material(blue_material)

belt.set_material(blue_material)

            </pre>
        </div>

    </div>

    <div class="grid-item">
            <div class="className" id='Ball Joint''>Ball Joint</div>
            
            <div class="methods">
            <div style="
            width: 50%;">Parts can be mated/jointed using Landmarks and Joints.</div>
            
            
            <pre>
            
from codetocad import *



ball = Part("ball").create_sphere(1)

ball_center = ball.create_landmark("center", center, center, center)

ball_bottom = ball.create_landmark("bottom", center, center, min)



link = Part("link").create_cube(1, 1, 2)

link_top = link.create_landmark("top", center, center, max)

link_bottom = link.create_landmark("bottom", center, center, min)



Joint(ball_center, link_bottom)\

    .limit_location_xyz(0, 0, 0).limit_rotation_xyz(0, 0, 0)



socket = Part("socket").create_sphere(1.2)

socket_cutoff = socket.create_landmark("cutoff", center, center, "min + 0.7")

socket_center = socket.create_landmark("center", center, center, center)



Joint(ball_bottom, socket_cutoff).translate_landmark_onto_another()



socket.subtract(ball, delete_after_subtract=False,

                is_transfer_landmarks=False)



Joint(socket_center, ball) \

    .limit_rotation_x(-30, 30) \

    .limit_rotation_y(-30, 30) \

    .limit_rotation_z(0, 0)





blue_material = Material("blue").set_color(0.0826006, 0.214978, 0.406714, 1.0)

green_material = Material("socket").set_color(

    0.249275, 0.709804, 0.392972, 0.8)

ball.set_material(blue_material)

link.set_material(blue_material)

socket.set_material(green_material)

            </pre>
        </div>

    </div>

    <div class="grid-item">
            <div class="className" id='Universal Joint''>Universal Joint</div>
            
            <div class="methods">
            <div style="
            width: 50%;">Parts can be mated/jointed using Landmarks and Joints.</div>
            
            
            <pre>
            
from dataclasses import dataclass

from codetocad import *



blue_metallic_material = Material("blue").set_color(

    0.0865257, 0.102776, 0.709804, 0.8).set_reflectivity(1.0)

red_metallic_material = Material("red").set_color(

    0.709804, 0.109394, 0.245126, 0.8).set_reflectivity(1.0)





@dataclass

class Yoke:

    '''

    A class that creates the arm of a universal joint:

    ___  ____________  __

   ( )                   )  < hollow rod

    ⁻⁻⁻  ⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻⁻  ⁻⁻

        ^             ^

     setScrew       pinHole

    '''

    shaft_radius: Dimension

    wall_thickness: Dimension

    shaft_length: Dimension



    pin_arm_length: Dimension

    pin_hole_radius: Dimension

    set_screw_radius: Dimension



    is_hollowed: bool = True



    def _createHollowRod(self, name: str, length: Dimension) -> Part:

        outerRadius = self.shaft_radius + self.wall_thickness



        rod = Part(name).create_cylinder(

            outerRadius, length)



        if self.is_hollowed:

            rod.hollow(self.wall_thickness, self.wall_thickness,

                       self.wall_thickness/2, flip_axis=True)



        _ = rod.create_landmark(

            "wallFront", center, f"min + {self.wall_thickness/4}", max)



        return rod



    def _create_shaft_coupling(self) -> Part:



        shaft_coupling = self._createHollowRod(

            "shaftCoupling", self.shaft_length)



        if self.is_hollowed:

            shaft_coupling.hole(shaft_coupling.get_landmark(PresetLandmark.back),

                                self.set_screw_radius, shaft_coupling.get_dimensions().y, normal_axis="y")



        return shaft_coupling



    def _create_pin_arm(self) -> Part:



        pin_arm = self._createHollowRod("pinArm", self.pin_arm_length)



        pin_arm_size = pin_arm.get_dimensions()



        pin_arm_discard_Amount = 1/15



        pin_arm.subtract(

            Part("pinArmDiscard").create_cube(

                pin_arm_size.x,

                pin_arm_size.y * (

                    1-pin_arm_discard_Amount),

                pin_arm_size.z + "1mm"

            ).translate_y(pin_arm_size.y * pin_arm_discard_Amount)

        )



        pin_arm.rotate_y(180)



        pin_location = pin_arm.create_landmark(

            "pin", center, min, "max -  (max-min) * 1/4")



        pin_arm.hole(pin_location,

                     self.pin_hole_radius, pin_arm_size.y, normal_axis="y", flip_axis=True)



        # pinArm.fillet_faces(

        #     "25mm",

        #     [pinArm.get_landmark(PresetLandmark.top)]

        # )



        return pin_arm



    def create(self, name: str) -> Part:



        shaft_coupling = self._create_shaft_coupling()



        pin_arm = self._create_pin_arm()



        Joint(

            shaft_coupling.get_landmark("wallFront"),

            pin_arm.get_landmark(

                "wallFront")

        ).limit_location_xyz(0, 0, 0)



        pin_arm.mirror(shaft_coupling, "y", None)



        shaft_coupling.get_landmark(PresetLandmark.top)



        yoke = shaft_coupling.union(

            pin_arm,

            is_transfer_landmarks=True

        )



        # shaftCoupling.fillet_faces(

        #     "25mm", [shaftCoupling.get_landmark(PresetLandmark.top)])



        yoke.rename(name)



        yoke.set_material(blue_metallic_material)



        return yoke





@dataclass

class Cross:



    width: Dimension

    pin_radius: Dimension

    pin_length: Dimension



    def create(self, name: str) -> Part:



        core = Part(name).create_cube(self.width, self.width, self.width)



        pin = Part("pin").create_cylinder(self.pin_radius, self.pin_length)



        Joint(

            core.get_landmark(PresetLandmark.top),

            pin.get_landmark(

                PresetLandmark.bottom)

        ).limit_location_xyz(0, 0, 0)



        pin.circular_pattern(

            4, 90, center_entity_or_landmark=core, normal_direction_axis="y")



        core = core.union(pin)



        core.rotate_x(90)



        core.set_material(red_metallic_material)



        return core





def create_universal_joint():



    shaft_radius = Dimension.from_string("5mm")

    wall_thickness = Dimension.from_string("3mm")

    shaft_length = Dimension.from_string("15mm")

    pin_arm_length = Dimension.from_string("13mm")

    pin_hole_radius = Dimension.from_string("2mm")

    set_screw_radius = Dimension.from_string("3mm")



    yokeBottom = Yoke(

        shaft_radius=shaft_radius,

        wall_thickness=wall_thickness,

        shaft_length=shaft_length,

        pin_arm_length=pin_arm_length,

        pin_hole_radius=pin_hole_radius,

        set_screw_radius=set_screw_radius

    ).create("yokeBottom")



    yoke_top = Yoke(

        shaft_radius=shaft_radius,

        wall_thickness=wall_thickness,

        shaft_length=shaft_length,

        pin_arm_length=pin_arm_length,

        pin_hole_radius=pin_hole_radius,

        set_screw_radius=set_screw_radius

    ).create("yokeTop")

    yoke_top.rotate_y(180)

    yoke_top.rotate_z(90)



    cross = Cross(

        width=shaft_radius,

        pin_radius=pin_hole_radius,

        pin_length=shaft_radius/2 + wall_thickness

    ).create("cross")



    Joint(

        cross.get_landmark(PresetLandmark.front),

        yokeBottom.get_landmark("pinArm_pin")

    ).limit_location_xyz(0, 0, 0).limit_rotation_xyz(0, None, 0).limit_rotation_y(-45, 45)



    Joint(

        cross.get_landmark(PresetLandmark.right),

        yoke_top.get_landmark("pinArm_pin")

    ).limit_location_xyz(0, 0, 0).limit_rotation_xyz(None, 0, 0).limit_rotation_x(-45, 45)





if __name__ == "__main__":



    create_universal_joint()

            </pre>
        </div>

    </div>

    <div class="grid-item">
            <div class="className" id='Double Universal Joint''>Double Universal Joint</div>
            
            <div class="methods">
            <div style="
            width: 50%;">Parts can be mated/jointed using Landmarks and Joints.</div>
            
            
            <pre>
            
from codetocad import *

from universal_joint import Yoke, Cross





def createDoubleuniversal_joint():



    shaft_radius = Dimension.from_string("5mm")

    wall_thickness = Dimension.from_string("3mm")

    shaft_length = Dimension.from_string("15mm")

    center_yold_length = Dimension.from_string("5mm")

    pin_arm_length = Dimension.from_string("13mm")

    pin_hole_radius = Dimension.from_string("2mm")

    set_screw_radius = Dimension.from_string("3mm")



    yoke_center = Yoke(

        shaft_radius=shaft_radius,

        wall_thickness=wall_thickness,

        shaft_length=center_yold_length,

        pin_arm_length=pin_arm_length,

        pin_hole_radius=pin_hole_radius,

        set_screw_radius=set_screw_radius,

        is_hollowed=False

    ).create("yokeCenter")

    yoke_center_pin_top = yoke_center.get_landmark("pinArm_pin")

    yoke_center_pin_top_location = yoke_center_pin_top.get_location_local()

    yoke_center_bottom_z = yoke_center.get_landmark(

        PresetLandmark.bottom).get_location_local().z

    yoke_center.mirror(yoke_center.get_landmark(

        PresetLandmark.bottom), "z", None)

    yoke_center_pin_bottom = yoke_center.create_landmark(

        "pinBottom", yoke_center_pin_top_location.x, yoke_center_pin_top_location.y, yoke_center_pin_top_location.z * -1 + yoke_center_bottom_z*2)



    yoke_top = Yoke(

        shaft_radius=shaft_radius,

        wall_thickness=wall_thickness,

        shaft_length=shaft_length,

        pin_arm_length=pin_arm_length,

        pin_hole_radius=pin_hole_radius,

        set_screw_radius=set_screw_radius

    ).create("yokeTop")

    yoke_top.rotate_y(180)

    yoke_top.rotate_z(90)



    yokeBottom = Yoke(

        shaft_radius=shaft_radius,

        wall_thickness=wall_thickness,

        shaft_length=shaft_length,

        pin_arm_length=pin_arm_length,

        pin_hole_radius=pin_hole_radius,

        set_screw_radius=set_screw_radius

    ).create("yokeBottom")

    yokeBottom.rotate_z(90)



    cross1 = Cross(

        width=shaft_radius,

        pin_radius=pin_hole_radius,

        pin_length=shaft_radius/2 + wall_thickness

    ).create("cross1")



    cross2 = Cross(

        width=shaft_radius,

        pin_radius=pin_hole_radius,

        pin_length=shaft_radius/2 + wall_thickness

    ).create("cross2")



    Joint(

        cross1.get_landmark(PresetLandmark.right),

        yoke_top.get_landmark("pinArm_pin"),

    ).limit_rotation_xyz(None, 0, 0).limit_rotation_x(-45, 45).limit_location_xyz(0, 0, 0)



    Joint(

        cross1.get_landmark(PresetLandmark.front), yoke_center_pin_top

    ).limit_rotation_xyz(0, None, 0).limit_rotation_y(-45, 45).limit_location_xyz(0, 0, 0)



    Joint(yoke_center_pin_bottom,

          cross2.get_landmark(PresetLandmark.front),

          ).limit_rotation_xyz(None, 0, 0).limit_rotation_x(-45, 45).limit_location_xyz(0, 0, 0)



    Joint(

        cross2.get_landmark(

            PresetLandmark.right), yokeBottom.get_landmark("pinArm_pin")

    ).limit_rotation_xyz(None, 0, 0).limit_rotation_x(-45, 45).limit_location_xyz(0, 0, 0)





if __name__ == "__main__":



    createDoubleuniversal_joint()

            </pre>
        </div>

    </div>

    <div class="grid-item">
            <div class="className" id='Simple Humanoid''>Simple Humanoid</div>
            
            <div class="methods">
            <div style="
            width: 50%;"></div>
            
            
            <pre>
            
from codetocad import *



# MARK: Create body

body = Part("body").create_cube(1, 2, 3)

body_top = body.create_landmark("top", center, center, max)



# MARK: Create head

head = Part("head").create_sphere(0.5)

head_bottom = head.create_landmark("bottom", center, center, min)



# Mark: Create Eye

eye = Part("eye").create_cylinder(0.1, 0.1)

eye_bottom = eye.create_landmark("bottom", center, center, min)



eye.rotate_xyz(0, 90, 0)



# Mark: Attach head to Body

Joint(body_top, head_bottom).limit_location_xyz(

    0, 0, 0).limit_location_y(-0.3, 0.3).limit_rotation_x(0, 0).limit_rotation_y(-20, 90).limit_rotation_z(-30, 30)



# Mark: Attach eye to head:

head_leftEye = head.create_landmark("leftEye", "max-0.1", -0.2, "max/3")

Joint(head_leftEye, eye_bottom).limit_location_xyz(

    0, 0, 0).limit_rotation_xyz(0, 0, 0)



# Mark: mirror the eyes

eye.mirror("head", "y", None)

            </pre>
        </div>

    </div>

    <div class="grid-item">
            <div class="className" id='Import and Export''>Import and Export</div>
            
            <div class="methods">
            <div style="
            width: 50%;">You can import files by using the createFromFile() method, and export Entities using the export() method. The filename extension will be used to guess the filetype, but you can specify a filetype too.</div>
            
            
            <pre>
            
from codetocad import *



imported_cube = Part("Imported Cube").createFromFile("./importableCube.stl")



Part("ExportedCube").create_cube(1, 1, 1)\

    .export("./exportedCube.stl")\

    .export("./exportedCube.obj")

            </pre>
        </div>

    </div>

    </div>

</body>

</html>