name: Check Capabilities JSON Exists

on:
  push:
    branches:
      - release

jobs:
  check-file-existence:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Get current Git commit epoch
      id: get_epoch
      run: echo "commit_epoch=$(git show -s --format=%ct HEAD)" >> $GITHUB_ENV

    - name: Check if capabilities JSON exists
      run: |
        FILE="docs/capabilities/capabilities_${{ env.commit_epoch }}.json"
        if [ -f "$FILE" ]; then
          echo "File $FILE exists."
        else
          echo "File $FILE does not exist."
          exit 1
        fi