on:
  push:
    branches:
      - develop

name: Create Blender Addon Zip File

jobs:
  build:
    name: Create Blender Addon Zip File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Assign Git Commit Epoch to $GITHUB_OUTPUT
        id: git_commit_epoch
        run: echo "GIT_COMMIT_EPOCH=$(git show -s --format=%ct HEAD)" >> "$GITHUB_OUTPUT"
      - name: Build Blender Addon Zip File
        run: sh ./createBlenderAddon.sh
      - name: Commit Blender Addon Zip File
        uses: EndBug/add-and-commit@v9
        with:
          author_name: ${{ vars.COMMIT_BOT_NAME }}
          author_email: ${{ vars.COMMIT_BOT_EMAIL }}
          fetch: false
          message: 'Release Blender Addon Zip File'
          pathspec_error_handling: exitImmediately

          tag: v0.2.${{ steps.git_commit_epoch.outputs.GIT_COMMIT_EPOCH }}
