name: lint

on: [push, pull_request]
jobs:
  auto-formatting-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"

