on:
  pull_request:
    types:
      - closed

name: Release Version and Blender Addon

jobs:
  create_release_tag:
    if: github.base_ref == 'develop' && github.head_ref == 'release/blenderAddonZipFile'
    name: Create release tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Assign Git Commit Epoch to $GITHUB_OUTPUT
        id: git_commit_epoch
        run: echo "GIT_COMMIT_EPOCH=$(git show -s --format=%ct HEAD)" >> "$GITHUB_OUTPUT"
      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v0.3.${{ steps.git_commit_epoch.outputs.GIT_COMMIT_EPOCH }}',
              sha: context.sha
            })
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v0.3.${{ steps.git_commit_epoch.outputs.GIT_COMMIT_EPOCH }}
          release_name: Release v0.3.${{ steps.git_commit_epoch.outputs.GIT_COMMIT_EPOCH }}
          body: "[PYPI Release](https://pypi.org/project/CodeToCAD/0.3.${{ steps.git_commit_epoch.outputs.GIT_COMMIT_EPOCH }}/)"
          draft: false
          prerelease: true
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: CodeToCADBlenderAddon.zip
          asset_name: CodeToCADBlenderAddon.zip
          tag: v0.3.${{ steps.git_commit_epoch.outputs.GIT_COMMIT_EPOCH }}
          overwrite: true
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
          pip install setuptools
      - name: Build package
        run: python setup.py sdist
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist/


  create_blender_addon_zip:
    if: github.base_ref == 'develop' && github.head_ref != 'release/blenderAddonZipFile' 
    name: Create Blender Addon Zip File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Blender Addon Zip File
        run: bash ./development/create_blender_addon.sh
      - run: git checkout -b release/blenderAddonZipFile
      - run: git add .
      - run: git config user.name ${{ vars.COMMIT_BOT_NAME }}
      - run: git config user.email ${{ vars.COMMIT_BOT_EMAIL }}
      - run: git commit -m "Release Blender Addon Zip File"
      - run: git push -u origin release/blenderAddonZipFile --force
      - name: create pull request
        run: gh pr create -B develop -H release/blenderAddonZipFile --title 'Blender Addon Zip File Release' --body 'Auto-created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
